#if !canImport(ObjectiveC)
import XCTest

extension MatchableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MatchableTests = [
        ("testArrays", testArrays),
        ("testBools", testBools),
        ("testDates", testDates),
        ("testDoubles", testDoubles),
        ("testInts", testInts),
        ("testOptionals", testOptionals),
        ("testStrings", testStrings),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MatchableTests.__allTests__MatchableTests),
    ]
}
#endif
